### ISSUE TITLE
Error: headers is blank on transporter.sendMail

### ISSUE THREAD

**Issue by last-core** [steve-lebleu/nodemailer-sendinblue-v3-transport#2]
Node.js version: v16.14.2
    "nodemailer": "^6.7.3",
    "nodemailer-sendinblue-v3-transport": "^1.0.1"
Currently I'm receiving this error from sendinblue, 
`message: {
    err: Error: headers is blank (missing_parameter, 400)
        at responseError (\node_modules\nodemailer-sendinblue-v3-transport\lib\nodemailer-sendinblue-v3-transport.js:335:10)
        at IncomingMessage.<anonymous> (\node_modules\nodemailer-sendinblue-v3-transport\lib\nodemailer-sendinblue-v3-transport.js:390:27)
        at IncomingMessage.emit (node:events:538:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
  },
  level: '\x1B[31merror\x1B[39m',
  timestamp: '2022-05-19T09:30:25.009Z'
}`
I've run some tests and it really is empty when I attempt to **console.log(data.headers)** on line 411, while on other hand **this.reqOptions.headers** has the entire object, replacing data.headers on line 421 with this.reqOptions.headers solves the problem and the request is successful, but I don't think it's the right solution in this case.

**Comment by last-core** [comment]
Nvm, just realized that the headers property needs to be passed with the sendMail object argument
